image: base/archlinux

stages:
  - package
  - install
  - test

pachage:
  stage: package
  script:
  - useradd ci
  - chown -R ci *
  - alias cido="sudo -u ci"
  - pacman -Sy --noconfirm archlinux-keyring
  - pacman -S --noconfirm sudo binutils fakeroot make cmake
  - cido makepkg
  artifacts:
    paths:
    - multiprocdown-*.tar.xz

install:
  stage: install
  script:
  - pacman -U --noconfirm multiprocdown-*.tar.xz

test:
   stage: test
  - cido multiprocdown -h
  - URL="https://root.cern.ch/root/html534/guides/users-guide/ROOTUsersGuideA4.pdf"
  - cido multiprocdown -u "$URL" -d -n 2 -o downfile.pdf
  - ls -l downfile.pdf
