stages:
- package

Arch:
  stage: package
  image: base/devel
  script:
  - useradd ci
  - chown -R ci *
  - pacman -Sy --noconfirm archlinux-keyring
  - pacman -S --noconfirm sudo binutils cmake
  - sudo -u ci makepkg
  artifacts:
    paths:
    - multiprocdown-*.tar.xz
