image: base/archlinux

stages:
  - package
  - test

pachage:
  stage: package
  script:
  - useradd ci
  - chown -R ci *
  - cido="sudo -u ci"
  - pacman -Sy --noconfirm archlinux-keyring
  - pacman -S --noconfirm sudo binutils fakeroot make cmake which
  - $cido makepkg
  artifacts:
    paths:
    - multiprocdown-*.tar.xz

test:
  stage: test
  script:
  - pacman -U --noconfirm multiprocdown-*.tar.xz
  - ls -l /usr/bin/multiprocdown
  - URL="https://root.cern.ch/root/html534/guides/users-guide/ROOTUsersGuideA4.pdf"
  - MD5="40ae503446d0a073a89e93864b1aa123"
  - $cido multiprocdown -u "$URL" -d -n 2 --md5=$MD5 -o downfile.pdf
  - ls -l downfile.pdf
  artifacts:
    paths:
    - downfile.pdf
    expire_in: 1 hrs
